
ADDED_C_FLG_DEF_INC	+= -I./inc

OBJECTS		+= oe_dbglog.o
OBJECTS		+= oe_location.o
OBJECTS		+= oe_os.o
OBJECTS		+= oe_tagscr.o
OBJECTS		+= oe_tagstr.o
OBJECTS		+= oe_tagvar.o
OBJECTS		+= oe_timeout.o
OBJECTS		+= oe_version.o

OBJECTS		+= oe_once.o

vpath %.c ./src
vpath %.cpp ./src

include ../makecfg.mk

